name: .NET

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
    - master
    - dev
   

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore 'backend/Messenger/Messenger.Api/Messenger.Api.csproj'
    - name: Build
      run: dotnet build 'backend/Messenger/Messenger.Api/Messenger.Api.csproj' --no-restore
