name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Build
      run: dotnet build backend/Messenger/Messenger.Api/Messenger.Api.csproj
    - name: Test
      run: dotnet test backend/Messenger/Messenger.Test.Api/Messenger.Test.Api.csproj  --no-build --verbosity normal
